In [1]:
import pandas as pd
import numpy as np

In [2]:
match = pd.read_pickle('bodyFace')
#match.to_csv('csvBodyFace')
uniqueNames = np.load('uniqueName.npy')

In [5]:
match.blur.min()

145.72244640751714

In [6]:
match.blur.max()

2645.5753328923252

In [7]:
def update1(s, uniqueNames, updateScore):
    for ind, n in enumerate(uniqueNames):
        updateScore[ind].append(s[n])

In [8]:
def update2(g, row, updateScore, uniqueNames):
    while g[g.seq == row.seq - i].empty:
        i = i + 1
    for ind, n in enumerate(uniqueNames):
        s = (row + g[g.seq == row.seq - i].values[0]) / 2 #Normally the condition g.seq == row.seq 
                                                          #should return only one result
        updateScore[ind].append(s)

In [9]:
def update3(uniqueNames, g, row, updateScore):
     for ind, n in enumerate(uniqueNames):
        alpha = 0.2 # shoud be tuned
        i = 1
        while g[g.seq == row.seq - i].empty or g[g.seq == row.seq - i].isnull().values.any():
            i = i + 1
        s = row[n] * alpha + g[g.seq == row.seq - i][n].values[0] * (1 - alpha)
        updateScore[ind].append(s)

In [10]:
# GroupBy per Id for update process
match2 = match.reset_index()

Creation of the ground truth for training model

In [11]:
match3 = match2.copy()

In [12]:
match3['GroundTrue'] = np.where(match2['id']==12, 'Cynthia', np.nan)

In [14]:
match3['GroundTrue'] = np.where(match2['id']==15, 'Sabrine', match3['GroundTrue'])

In [27]:
#match3.to_pickle('MLbodyFace')

In [9]:
match2

,seq,id,traSeq,trackId,trackX,trackY,trackW,trackH,height,distance,rgbSeq,Laurene,Anthony,Wissem,Cynthia,Sabrine,blur
0,784,12,784,12,238.0,278.0,336.6,396.0,1.597804,2.993590,0,1.341175,1.302884,1.315100,1.046635,1.339248,663.778234
1,784,14,784,14,81.6,400.0,91.8,108.0,0.803921,5.991756,0,NaN,NaN,NaN,NaN,NaN,NaN
2,785,12,785,12,217.6,276.0,343.4,406.0,1.598425,2.921760,0,NaN,NaN,NaN,NaN,NaN,NaN
3,785,14,785,14,81.6,400.0,91.8,108.0,0.803921,5.991756,0,NaN,NaN,NaN,NaN,NaN,NaN
4,786,12,786,12,193.8,276.0,357.0,420.0,1.599651,2.825866,3,1.297213,1.228618,1.401256,0.710368,1.398127,395.108355
5,786,14,786,14,81.6,400.0,91.8,108.0,0.803921,5.991756,3,NaN,NaN,NaN,NaN,NaN,NaN
6,787,12,787,12,170.0,276.0,367.2,432.0,1.598773,2.788292,5,1.257040,1.269675,1.339069,0.772881,1.326457,275.320893
7,787,14,787,14,81.6,400.0,91.8,108.0,0.803921,5.991756,5,NaN,NaN,NaN,NaN,NaN,NaN
8,788,12,788,12,163.2,278.0,370.6,436.0,1.598104,2.776649,6,1.270489,1.265388,1.339574,0.756341,1.361371,291.272770
9,788,14,788,14,81.6,400.0,91.8,108.0,0.803921,5.991756,6,NaN,NaN,NaN,NaN,NaN,NaN
10,789,12,789,12,156.4,280.0,374.0,440.0,1.597755,2.751087,6,NaN,NaN,NaN,NaN,NaN,NaN
11,789,14,789,14,81.6,400.0,91.8,108.0,0.803921,5.991756,6,NaN,NaN,NaN,NaN,NaN,NaN
12,790,12,790,12,146.2,282.0,377.4,446.0,1.597284,2.733374,7,1.159458,1.226889,1.274342,0.774507,1.388032,398.074038
13,790,14,790,14,81.6,400.0,91.8,108.0,0.803921,5.991756,7,NaN,NaN,NaN,NaN,NaN,NaN
14,791,12,791,12,142.8,284.0,380.8,450.0,1.597968,2.722706,8,1.230790,1.286956,1.278533,0.781219,1.344135,555.155143
15,791,14,791,14,81.6,400.0,91.8,108.0,0.803921,5.991756,8,NaN,NaN,NaN,NaN,NaN,NaN
16,792,12,792,12,122.4,284.0,394.4,464.0,1.596457,2.655667,8,NaN,NaN,NaN,NaN,NaN,NaN
17,792,14,792,14,81.6,400.0,91.8,108.0,0.803921,5.991756,8,NaN,NaN,NaN,NaN,NaN,NaN
18,793,12,793,12,112.2,284.0,404.6,478.0,1.594237,2.590717,9,1.206173,1.248794,1.242732,0.760098,1.361885,424.413457
19,793,14,793,14,81.6,400.0,91.8,108.0,0.803921,5.991756,9,NaN,NaN,NaN,NaN,NaN,NaN
20,794,12,794,12,115.6,286.0,414.8,488.0,1.592291,2.487561,11,1.207176,1.250816,1.254134,0.807621,1.354820,512.477635
21,794,14,794,14,81.6,400.0,91.8,108.0,0.803921,5.991756,11,NaN,NaN,NaN,NaN,NaN,NaN
22,795,12,795,12,136.0,288.0,418.2,494.0,1.590862,2.418992,12,1.238172,1.225516,1.232129,0.800250,1.347640,542.142234
23,795,14,795,14,81.6,400.0,91.8,108.0,0.803921,5.991756,12,NaN,NaN,NaN,NaN,NaN,NaN
24,796,12,796,12,146.2,288.0,421.6,498.0,1.592582,2.341361,12,NaN,NaN,NaN,NaN,NaN,NaN
25,796,14,796,14,81.6,400.0,91.8,108.0,0.803921,5.991756,12,NaN,NaN,NaN,NaN,NaN,NaN
26,797,12,797,12,159.8,290.0,428.4,506.0,1.594597,2.298524,12,NaN,NaN,NaN,NaN,NaN,NaN
27,797,14,797,14,81.6,400.0,91.8,108.0,0.803921,5.991756,12,NaN,NaN,NaN,NaN,NaN,NaN
28,798,12,798,12,180.2,290.0,442.0,520.0,1.595444,2.283207,13,1.267545,1.220619,1.211027,0.813766,1.321908,557.726855
29,798,14,798,14,81.6,400.0,91.8,108.0,0.803921,5.991756,13,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
727,1137,17,1137,17,1186.6,616.0,119.0,140.0,0.494020,2.573133,378,NaN,NaN,NaN,NaN,NaN,NaN
728,1138,12,1138,12,547.4,262.0,397.8,470.0,1.583883,2.319799,379,1.126352,1.362851,1.212077,1.096382,1.282677,1472.346088
729,1138,15,1138,15,673.2,318.0,275.4,326.0,1.538408,3.255186,379,1.321085,1.393272,1.249898,1.050840,1.383428,1257.004671
730,1138,17,1138,17,1186.6,616.0,119.0,140.0,0.494020,2.573133,379,NaN,NaN,NaN,NaN,NaN,NaN
731,1141,12,1141,12,547.4,262.0,397.8,470.0,1.583883,2.319799,382,NaN,NaN,NaN,NaN,NaN,NaN
732,1141,15,1141,15,615.4,322.0,261.8,310.0,1.531690,3.379526,382,1.124619,1.363815,1.299372,1.055904,1.367269,1489.028013
733,1142,12,1142,12,710.6,264.0,404.6,478.0,1.584980,2.249599,386,NaN,NaN,NaN,NaN,NaN,NaN
734,1142,15,1142,15,588.2,320.0,261.8,310.0,1.529408,3.340304,386,1.068888,1.403688,1.335710,1.199142,1.336338,1343.042359
735,1143,12,1143,12,724.2,270.0,401.2,474.0,1.586450,2.234758,386,NaN,NaN,NaN,NaN,NaN,NaN
736,1143,15,1143,15,574.6,318.0,261.8,310.0,1.524919,3.354659,386,NaN,NaN,NaN,NaN,NaN,NaN
737,1144,12,1144,12,771.8,272.0,401.2,474.0,1.588640,2.246878,388,NaN,NaN,NaN,NaN,NaN,NaN
738,1144,15,1144,15,557.6,316.0,261.8,310.0,1.524032,3.373454,388,1.021551,1.458244,1.320867,1.112545,1.370967,1553.126501
739,1145,12,1145,12,785.4,274.0,401.2,472.0,1.591561,2.254036,388,NaN,NaN,NaN,NaN,NaN,NaN
740,1145,15,1145,15,550.8,316.0,261.8,310.0,1.523025,3.387116,388,NaN,NaN,NaN,NaN,NaN,NaN
741,1146,12,1146,12,822.8,276.0,401.2,472.0,1.593780,2.266992,391,NaN,NaN,NaN,NaN,NaN,NaN
742,1146,15,1146,15,530.4,314.0,265.2,312.0,1.525077,3.374292,391,0.991501,1.448605,1.299343,1.105491,1.356849,1459.518927
743,1147,12,1147,12,884.0,280.0,397.8,468.0,1.595187,2.330174,392,NaN,NaN,NaN,NaN,NaN,NaN
744,1147,15,1147,15,506.6,312.0,268.6,316.0,1.521795,3.301697,392,0.918309,1.372948,1.278330,1.039204,1.317150,1476.856415
745,1148,12,1148,12,897.6,282.0,394.4,464.0,1.594968,2.358399,392,NaN,NaN,NaN,NaN,NaN,NaN
746,1148,15,1148,15,499.8,312.0,268.6,318.0,1.518905,3.273517,392,NaN,NaN,NaN,NaN,NaN,NaN
747,1149,12,1149,12,921.4,284.0,391.0,460.0,1.595612,2.393583,394,NaN,NaN,NaN,NaN,NaN,NaN
748,1149,15,1149,15,482.8,310.0,275.4,324.0,1.519630,3.236356,394,0.967987,1.399766,1.338986,1.163881,1.267676,1255.901825
749,1150,12,1150,12,931.6,286.0,387.6,456.0,1.594318,2.403975,394,NaN,NaN,NaN,NaN,NaN,NaN
750,1150,15,1150,15,479.4,310.0,275.4,326.0,1.517675,3.211425,394,NaN,NaN,NaN,NaN,NaN,NaN
751,1151,12,1151,12,979.2,288.0,380.8,450.0,1.596626,2.475729,394,NaN,NaN,NaN,NaN,NaN,NaN
752,1151,15,1151,15,452.2,308.0,285.6,336.0,1.520363,3.154896,394,NaN,NaN,NaN,NaN,NaN,NaN
753,1152,12,1152,12,999.6,288.0,377.4,444.0,1.599931,2.556006,394,NaN,NaN,NaN,NaN,NaN,NaN
754,1152,15,1152,15,442.0,306.0,292.4,344.0,1.524022,3.074744,394,NaN,NaN,NaN,NaN,NaN,NaN
755,1153,12,1153,12,1030.2,290.0,370.6,436.0,1.602403,2.586752,394,NaN,NaN,NaN,NaN,NaN,NaN
756,1153,15,1153,15,421.6,304.0,299.2,354.0,1.527658,3.056095,394,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
previousB = match2['blur'].shift(-1)[:-1].dropna()

In [30]:
len(previousB)

359

In [33]:
currentB = match2['blur'].dropna()[:-1]

In [34]:
len(currentB)

359

In [27]:
match2['blur'][:-1].dropna()

0       663.778234
4       395.108355
6       275.320893
8       291.272770
12      398.074038
14      555.155143
18      424.413457
20      512.477635
22      542.142234
28      557.726855
30      568.922130
32      968.980012
34      514.322164
36      644.856759
38      945.655805
40     1062.450460
44     1316.370508
66      336.891664
67      333.676233
69      306.882823
70      316.361924
71      175.323780
73      267.926870
77      504.955646
80      934.220257
82      973.555821
84      598.976513
88      886.737089
90      785.424957
92      703.988691
          ...
644     340.505296
645    1665.415019
646     365.182604
647    1495.704166
653    2063.140726
656    2333.684807
662    1473.523265
665    1626.178967
668    1751.905057
671    1351.815619
674    1220.346212
677    1289.825035
683    1019.569117
689    1075.575547
696    1234.223080
699    1644.026555
705    1186.976627
708     932.235416
711    1650.752970
714    1764.757928
720    2249.967092
723     213.656717
728    1472.346088
729    1257.004671
732    1489.028013
734    1343.042359
738    1553.126501
742    1459.518927
744    1476.856415
748    1255.901825
Name: blur, Length: 360, dtype: float64

In [24]:
diffB = previousB - match2['blur'][:-1].dropna()

In [25]:
diffB

0             NaN
3             NaN
4             NaN
5             NaN
6             NaN
7             NaN
8             NaN
11            NaN
12            NaN
13            NaN
14            NaN
17            NaN
18            NaN
19            NaN
20            NaN
21            NaN
22            NaN
27            NaN
28            NaN
29            NaN
30            NaN
31            NaN
32            NaN
33            NaN
34            NaN
35            NaN
36            NaN
37            NaN
38            NaN
39            NaN
          ...
696           NaN
698           NaN
699           NaN
704           NaN
705           NaN
707           NaN
708           NaN
710           NaN
711           NaN
713           NaN
714           NaN
719           NaN
720           NaN
722           NaN
723           NaN
727           NaN
728   -215.341418
729           NaN
731           NaN
732           NaN
733           NaN
734           NaN
737           NaN
738           NaN
741           NaN
742           NaN
743           NaN
744           NaN
747           NaN
748           NaN
Name: blur, Length: 525, dtype: float64

In [19]:
previousL = match2['Laurene'].shift(-1)[:-1]

In [10]:
match2[np.concatenate((uniqueNames, ['blur']), axis=0)]

      Laurene   Anthony    Wissem   Cynthia   Sabrine         blur
0    1.341175  1.302884  1.315100  1.046635  1.339248   663.778234
1         NaN       NaN       NaN       NaN       NaN          NaN
2         NaN       NaN       NaN       NaN       NaN          NaN
3         NaN       NaN       NaN       NaN       NaN          NaN
4    1.297213  1.228618  1.401256  0.710368  1.398127   395.108355
5         NaN       NaN       NaN       NaN       NaN          NaN
6    1.257040  1.269675  1.339069  0.772881  1.326457   275.320893
7         NaN       NaN       NaN       NaN       NaN          NaN
8    1.270489  1.265388  1.339574  0.756341  1.361371   291.272770
9         NaN       NaN       NaN       NaN       NaN          NaN
10        NaN       NaN       NaN       NaN       NaN          NaN
11        NaN       NaN       NaN       NaN       NaN          NaN
12   1.159458  1.226889  1.274342  0.774507  1.388032   398.074038
13        NaN       NaN       NaN       NaN       NaN          NaN
14   1.230790  1.286956  1.278533  0.781219  1.344135   555.155143
15        NaN       NaN       NaN       NaN       NaN          NaN
16        NaN       NaN       NaN       NaN       NaN          NaN
17        NaN       NaN       NaN       NaN       NaN          NaN
18   1.206173  1.248794  1.242732  0.760098  1.361885   424.413457
19        NaN       NaN       NaN       NaN       NaN          NaN
20   1.207176  1.250816  1.254134  0.807621  1.354820   512.477635
21        NaN       NaN       NaN       NaN       NaN          NaN
22   1.238172  1.225516  1.232129  0.800250  1.347640   542.142234
23        NaN       NaN       NaN       NaN       NaN          NaN
24        NaN       NaN       NaN       NaN       NaN          NaN
25        NaN       NaN       NaN       NaN       NaN          NaN
26        NaN       NaN       NaN       NaN       NaN          NaN
27        NaN       NaN       NaN       NaN       NaN          NaN
28   1.267545  1.220619  1.211027  0.813766  1.321908   557.726855
29        NaN       NaN       NaN       NaN       NaN          NaN
..        ...       ...       ...       ...       ...          ...
727       NaN       NaN       NaN       NaN       NaN          NaN
728  1.126352  1.362851  1.212077  1.096382  1.282677  1472.346088
729  1.321085  1.393272  1.249898  1.050840  1.383428  1257.004671
730       NaN       NaN       NaN       NaN       NaN          NaN
731       NaN       NaN       NaN       NaN       NaN          NaN
732  1.124619  1.363815  1.299372  1.055904  1.367269  1489.028013
733       NaN       NaN       NaN       NaN       NaN          NaN
734  1.068888  1.403688  1.335710  1.199142  1.336338  1343.042359
735       NaN       NaN       NaN       NaN       NaN          NaN
736       NaN       NaN       NaN       NaN       NaN          NaN
737       NaN       NaN       NaN       NaN       NaN          NaN
738  1.021551  1.458244  1.320867  1.112545  1.370967  1553.126501
739       NaN       NaN       NaN       NaN       NaN          NaN
740       NaN       NaN       NaN       NaN       NaN          NaN
741       NaN       NaN       NaN       NaN       NaN          NaN
742  0.991501  1.448605  1.299343  1.105491  1.356849  1459.518927
743       NaN       NaN       NaN       NaN       NaN          NaN
744  0.918309  1.372948  1.278330  1.039204  1.317150  1476.856415
745       NaN       NaN       NaN       NaN       NaN          NaN
746       NaN       NaN       NaN       NaN       NaN          NaN
747       NaN       NaN       NaN       NaN       NaN          NaN
748  0.967987  1.399766  1.338986  1.163881  1.267676  1255.901825
749       NaN       NaN       NaN       NaN       NaN          NaN
750       NaN       NaN       NaN       NaN       NaN          NaN
751       NaN       NaN       NaN       NaN       NaN          NaN
752       NaN       NaN       NaN       NaN       NaN          NaN
753       NaN       NaN       NaN       NaN       NaN          NaN
754       NaN       NaN       NaN       NaN       NaN          NaN
755       NaN       NaN       NaN       NaN       NaN          NaN
756       NaN       NaN       NaN       NaN       NaN          NaN

[757 rows x 6 columns]

In [11]:
# Create empty list that will be fulfilled by updated FR score
updateScore = [[] for i in range(len(uniqueNames))]

big = []
for i, g in match2.groupby('id'):
    print g.id.iloc[0]
    print g[g.blur < 1000][np.concatenate((uniqueNames, ['blur']), axis=0)].dropna().rolling(window=[0.8,0.2], win_type='boxcar').mean()
    right = g[g.blur < 1000][np.concatenate((uniqueNames, ['blur']), axis=0)].dropna().rolling(window=[0.8,0.2], win_type='boxcar').mean().dropna()

    big.append(right)
    #match2 = pd.merge(match2, right, how='left', on='id', suffixes=('a', 'b'))
result = pd.concat(big)

12
      Laurene   Anthony    Wissem   Cynthia   Sabrine        blur
0         NaN       NaN       NaN       NaN       NaN         NaN
4    1.332383  1.288031  1.332331  0.979382  1.351024  610.044258
6    1.289178  1.236829  1.388819  0.722871  1.383793  371.150862
8    1.259730  1.268817  1.339170  0.769573  1.333440  278.511268
12   1.248283  1.257688  1.326527  0.759974  1.366704  312.633024
14   1.173725  1.238903  1.275180  0.775850  1.379253  429.490259
18   1.225867  1.279324  1.271373  0.776995  1.347685  529.006806
20   1.206373  1.249199  1.245012  0.769602  1.360472  442.026293
22   1.213375  1.245756  1.249733  0.806147  1.353384  518.410555
28   1.244047  1.224537  1.227909  0.802953  1.342493  545.259158
30   1.267282  1.234427  1.220268  0.826112  1.326022  559.965910
32   1.272683  1.296608  1.255596  0.885806  1.340658  648.933706
34   1.299631  1.322328  1.247979  0.934553  1.337187  878.048443
36   1.298038  1.313858  1.248668  0.951814  1.349349  540.429083
38   1.280869  1.308959  1.263629  0.920007  1.338310  705.016569
66   1.260269  1.284390  1.234995  0.978508  1.317176  823.902977
67   1.060992  1.240018  1.180808  0.924220  1.218957  336.248578
69   1.093368  1.207315  1.127897  1.012051  1.249474  328.317551
70   1.164956  1.271788  1.207890  1.008894  1.272588  308.778643
71   1.245483  1.275852  1.212117  0.998898  1.280692  288.154296
80   1.238255  1.300536  1.218841  0.995281  1.307101  327.103075
82   1.262163  1.307497  1.241210  0.898693  1.370221  942.087370
84   1.251571  1.298947  1.224547  0.880833  1.350981  898.639960
88   1.223008  1.254375  1.267468  0.856710  1.338020  656.528628
90   1.302660  1.232005  1.246307  0.993359  1.323648  866.474663
92   1.331626  1.273435  1.253629  0.995631  1.342967  769.137704
94   1.325887  1.210856  1.203854  0.950554  1.320808  755.692452
148  1.308859  1.268306  1.234832  1.009568  1.342668  965.024835
162  1.227417  1.236310  1.283514  0.877471  1.374238  962.107786
182  1.275056  1.280224  1.222894  0.890939  1.293664  813.924616
..        ...       ...       ...       ...       ...         ...
264  1.285411  1.306577  1.260267  0.903138  1.379617  912.634567
266  1.268823  1.230474  1.240720  0.808438  1.344064  897.646571
268  1.238751  1.174876  1.237192  0.835002  1.339424  896.541955
272  1.243834  1.150791  1.313430  0.824928  1.352120  910.487224
274  1.293414  1.175708  1.230076  0.887801  1.328928  955.867560
276  1.287106  1.249053  1.243917  0.861635  1.348993  978.494583
344  1.269067  1.255521  1.229177  0.808571  1.329121  964.385625
348  1.250813  1.251950  1.216065  0.783711  1.333975  873.864903
364  1.269408  1.285010  1.227975  0.909822  1.326258  737.701300
368  1.213070  1.347226  1.286671  1.060697  1.313437  436.217924
402  1.246783  1.276507  1.258325  0.959344  1.316695  358.906898
426  1.210775  1.299164  1.214760  1.060242  1.251833  553.473994
453  1.166166  1.317399  1.295904  1.106745  1.303952  737.881554
459  1.265413  1.286350  1.272632  0.814420  1.349264  426.071157
471  1.290371  1.216445  1.262611  0.852589  1.388355  544.311839
474  1.266803  1.200942  1.246290  0.956105  1.314471  562.129028
479  1.247501  1.293677  1.217257  1.081447  1.229557  226.514094
527  1.249556  1.345432  1.299215  1.190840  1.173563  323.430735
553  1.286682  1.318164  1.237305  0.922508  1.356696  864.855682
579  1.304123  1.361824  1.233622  1.026155  1.379004  703.256310
599  1.241847  1.294187  1.204113  0.938186  1.298564  832.384190
601  1.233167  1.251753  1.217507  0.843547  1.351681  572.750334
603  1.231912  1.237420  1.262709  0.767373  1.360465  490.160255
607  1.247863  1.216207  1.271517  0.725314  1.312312  580.107536
617  1.265096  1.276329  1.280267  0.878155  1.286458  694.547804
621  1.159347  1.350352  1.243657  1.181483  1.192995  486.248646
623  1.134864  1.346508  1.202483  1.167297  1.178837  466.200978
625  1.046231  1.366961  1.249790  1.126952  1.219590  482.857668
627  1.081571  1.364382  1.290691  1.055615  1.251644  526.831175
629  1.197212  1.256956  1.269213  0.841213  1.389796  960.032040

[67 rows x 6 columns]
14
Empty DataFrame
Columns: [Laurene, Anthony, Wissem, Cynthia, Sabrine, blur]
Index: []
15
      Laurene   Anthony    Wissem   Cynthia   Sabrine        blur
73        NaN       NaN       NaN       NaN       NaN         NaN
77   1.278896  1.318041  1.240451  1.027864  1.296197  315.332625
137  1.276508  1.294591  1.240633  0.999059  1.296957  443.681488
141  1.291856  1.365400  1.249078  1.123322  1.293347  200.309393
143  1.324016  1.400319  1.203497  1.247226  1.250812  210.079306
145  1.275893  1.385675  1.151293  1.246850  1.125113  235.140763
147  1.132121  1.349165  1.182860  1.225859  1.099096  299.957881
149  1.132945  1.348395  1.247838  1.222990  1.135934  358.813206
151  1.070088  1.398043  1.290577  1.203489  1.249638  428.110076
155  1.122561  1.374154  1.265096  1.216851  1.142984  427.177952
157  1.177790  1.384543  1.244457  1.263102  1.155313  376.911827
159  1.223376  1.386512  1.311118  1.153052  0.962990  336.899884
163  1.254801  1.384174  1.253837  1.185758  0.996328  369.391550
165  1.218982  1.382873  1.223966  1.235017  0.971942  391.313996
167  1.213317  1.409409  1.277564  1.228030  0.975701  347.528812
171  1.262604  1.391617  1.259749  1.236771  0.994994  345.203869
173  1.326822  1.384105  1.224318  1.277778  0.993422  344.817317
175  1.315419  1.340925  1.211361  1.284124  1.092010  388.203537
179  1.311974  1.318658  1.218767  1.204526  1.175206  482.671494
181  1.254913  1.257879  1.217735  0.865717  1.312297  513.861662
183  1.254536  1.280265  1.247016  0.871796  1.304618  520.673334
185  1.273409  1.281518  1.228399  0.961672  1.337796  344.828628
187  1.273174  1.268242  1.219887  0.950485  1.325555  338.459954
191  1.271341  1.315688  1.219174  1.006505  1.312267  358.695042
193  1.358966  1.403621  1.146465  1.269429  1.194844  495.899124
219  1.338147  1.405831  1.169959  1.236356  1.219364  481.226110
223  1.287003  1.335877  1.240289  1.123344  1.314181  544.024589
225  1.231222  1.288737  1.206610  0.974515  1.241816  516.569722
227  1.202745  1.264968  1.222732  0.944443  1.245039  489.270396
229  1.247268  1.227722  1.191313  0.935978  1.255058  497.849278
..        ...       ...       ...       ...       ...         ...
526  1.357134  1.433179  1.308540  1.206552  1.191692  249.936995
528  1.199242  1.368082  1.219105  1.131467  1.131240  314.744668
530  1.138406  1.379243  1.273078  1.157809  1.006453  317.769462
532  1.058363  1.389284  1.211024  1.113677  1.046055  397.464796
534  1.123535  1.422837  1.183200  1.122444  1.149917  439.861234
538  1.119983  1.409410  1.218233  1.107734  1.140199  240.455524
540  1.108800  1.391847  1.239142  1.160180  1.251581  345.292357
544  1.025132  1.426808  1.295976  1.150489  1.349018  472.708505
546  1.078661  1.375796  1.226051  1.085967  1.328952  622.227960
550  1.266650  1.288988  1.231542  0.935725  1.330667  757.787695
552  1.267516  1.312590  1.237908  0.926219  1.336403  743.044044
576  1.274225  1.321683  1.268956  1.032634  1.318672  967.191514
578  1.136462  1.406234  1.325537  1.205254  1.199910  948.351721
608  1.189403  1.289910  1.230978  0.935244  1.298868  931.958742
610  1.297892  1.292258  1.215388  1.019311  1.309697  675.090867
612  1.225984  1.253708  1.212795  0.956451  1.278306  418.945514
614  1.176729  1.295092  1.249669  1.060196  1.247508  358.154586
616  1.181747  1.335934  1.261657  1.090068  1.248882  437.140533
622  1.225617  1.318852  1.257051  1.084906  1.210984  543.809113
628  1.273955  1.323276  1.306808  1.007940  1.355274  799.751544
630  1.010781  1.374490  1.253010  1.108671  1.227271  503.403290
634  1.000450  1.370570  1.257258  1.104334  1.249752  438.061056
636  0.959033  1.403171  1.248297  1.152320  1.219938  304.950743
638  0.968385  1.418481  1.271989  1.159306  1.171715  280.611179
640  0.996843  1.415217  1.262241  1.172476  1.127793  266.826475
642  1.059397  1.418194  1.218801  1.194713  1.080035  255.720367
644  1.201556  1.423665  1.191617  1.258580  0.993064  284.441386
646  1.313350  1.398769  1.296591  1.273498  1.203370  345.440758
708  1.281274  1.265118  1.217355  0.985384  1.319428  478.593166
723  1.263134  1.237296  1.204423  0.829951  1.333825  788.519676

[125 rows x 6 columns]
16
Empty DataFrame
Columns: [Laurene, Anthony, Wissem, Cynthia, Sabrine, blur]
Index: []
17
Empty DataFrame
Columns: [Laurene, Anthony, Wissem, Cynthia, Sabrine, blur]
Index: []

In [12]:
pd.merge(match2, residue, how='left', left_index=True, right_index=True, suffixes=('a', 'b'))

NameError: name 'residue' is not defined

In [ ]:
pd.merge(match2, result, how='left', left_index=True, right_index=True, suffixes=('a', 'b'))

In [ ]:
result

In [ ]:
big[2]